layout_spectrum: 0.6223091203719378
typography_spectrum: 0.2600719244219363
color:
  saturation: 0.8382978
  brandStrength: 0.3382979
  lightness: 0.3808511
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  rhythmicContrast: 0.7595745
title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: ''
navigation:
  - name: Home
    url: 'http://scs.vteducator.com/'
    type: external
  - name: JumpRope
    id: 2effb55e-c46f-49fa-9a16-c2212f7ce9b6
    type: content
  - name: Contact
    id: 55145417-7f4b-4c78-a93b-80b1ad042878
    type: content
  - name: Subscribe
    url: >-
      http://vteducator.us13.list-manage1.com/subscribe?u=2b810cf5360242dcc50ed2227&id=5ab54d2b8b&orig-lang=1
    type: external
analytics:
  google: UA-59206840-2
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/20c91f2a-8206-49b5-aefc-1954eea0fcb7.jpg
author:
  url: vteducator.com
  name: vteducator.com
  email: jbadillo@cssu.org
name: SCS
logo: null
