typography_spectrum: 0.8227087962441146
color:
  brandStrength: 0.5636555966921151
  lightness: 0.7350331731140614
  saturation: 0.7663038189057261
  rhythmicContrast: 0.5260739298537374
  brandColors:
    - '#729356'
    - '#426139'
    - '#92BD3F'
    - '#FFFFFF'
    - '#DDD08D'
layout_spectrum: 0.7958448715507984
author:
  url: vteducator.com
  name: vteducator.com
name: how-tos
navigation:
  - name: Home
    url: 'http://scs.vteducator.com/'
    type: external
  - name: JumpRope
    id: 2effb55e-c46f-49fa-9a16-c2212f7ce9b6
    type: content
  - name: Contact
    id: 55145417-7f4b-4c78-a93b-80b1ad042878
    type: content
  - name: Subscribe
    url: >-
      http://vteducator.us13.list-manage1.com/subscribe?u=2b810cf5360242dcc50ed2227&id=5ab54d2b8b&orig-lang=1
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/20c91f2a-8206-49b5-aefc-1954eea0fcb7.jpg
title: Technology Integration
description: Shelburne Community School
